### ISSUE TITLE
onnx conversion

### ISSUE THREAD

**Issue by preste-nakam** [xmed-lab/CLIP_Surgery#11]
Hello
Thanks for the great work.
Do you have a script to convert your CLIP_Surgery to onnx format ?

**Comment by Eli-YiLi** [comment]
Sorry, I am not familiar with onnx.

I guess some operations may influence the conversion. Firstly, I merge results of two paths as final image features (cls token from original path, and image tokens from new path). Besides, I write dual path in a single block via a list input and output. 

If it matters to model conversion. Maybe it's easier to return two outputs, and treat other parts as post-processing like results merging and feature surgery. Besides, if dual paths in single block is not suitable to conversion, please rewrite it as two blocks.
