### ISSUE TITLE
Aquire about open-vocabulary segmentation implementation

### ISSUE THREAD

**Issue by lwpyh** [xmed-lab/CLIP_Surgery#25]
Hi, thanks for this great work, I've noticed that clip_surgery also achieves good performance in open-vocabulary segmentation. However, clip_surgery requires specific words as input to obtain the corresponding segmentation results. I'd like to ask how clip_surgery is implemented in the open-vocabulary segmentation setting?

**Comment by Eli-YiLi** [comment]
Given N texts (classes), then you need to get the similarity maps for each class. Finally, apply argmax operation to get the segmentation label. Note, only the output of new path from architecture surgery is used, the feature surgery doesn't change the top1 rank.
