### ISSUE TITLE
Design of the category weight w.

### ISSUE THREAD

**Issue by ByChelsea** [xmed-lab/CLIP_Surgery#26]
Hi! Thanks for your great work.
Could you please provide a detailed explanation of how the category weight 'w' in formula (7) is designed? Why is it crucial to emphasize obvious classes?

**Comment by Eli-YiLi** [comment]
Sorry for late reply.

For the obvious categories, we find some categories take the lead and appear together with others (e.g. bike and person)
Emphasize more on obvious help to reduce such relation in some degree empirically.
