### ISSUE TITLE
About mSC

### ISSUE THREAD

**Issue by lwpyh** [xmed-lab/CLIP_Surgery#27]
Hi, Thank u for your great works!  I just want to ask about the exact definition of $m_c$ and $m_s$ in metric mSC, could you provide a specific example to illustrate it? Thank you again!

**Comment by Eli-YiLi** [comment]
Please refer to the new equation:
![image](https://github.com/xmed-lab/CLIP_Surgery/assets/49093246/8a00671c-9ea0-47df-b5f1-dd6e40152476)
