### ISSUE TITLE
custom pretrained weights 

### ISSUE THREAD

**Issue by Tinaliu123** [xmed-lab/CLIP_Surgery#31]
Can I load my custom pretrained weights by providing the path to the weights when I load the mode?

**Comment by zer0int** [comment]
I just so happened to implement that yesterday in my fork, for the same reasons (using my fine-tune with it).
You can replace (temporarily rename) the original pre-trained CLIP model in .cache/clip and put your fine-tune of the same model in place of it (though you could also modify the code to use torch.load and just load the pickle / .pt from somewhere else instead):

[https://github.com/zer0int/CLIP_Surgery](https://github.com/zer0int/CLIP_Surgery)
