### ISSUE TITLE
question about section 5.6 in the paper

### ISSUE THREAD

**Issue by xiexie123** [xmed-lab/CLIP_Surgery#5]
你好，
      论文中5.6不是很明白。clip在训练的时候是句子和图片pair。如何得到每个单词与图片的相似度的呢？等式(9)里的Nt，是text token数量，那么在5.6的实验中，把句子中的每个单词作为text token吗？

**Comment by Eli-YiLi** [comment]
In CLIP the one sentence (n words) is embedded with a start token and an end token, and the output shape is (n + 2) * channel.
Then CLIP uses argmax operation across (n + 2) dimension to select the finial text features.
We use the text features before argmax in exp 5.6.
And N_t in other subsections indicates features for multiple sentences after argmax.
