### ISSUE TITLE
Error _ Can you help me? 

### ISSUE THREAD

**Issue by federicofloresh** [xmed-lab/CLIP_Surgery#6]
I have an error in jupyter :

AttributeError: module 'clip' has no attribute 'encode_text_with_prompt_ensemble'

"encode_text_with_prompt_ensemble" is a function? How can i solve it ? 

Thanks!

**Comment by federicofloresh** [comment]
Solved it !

**Comment by Sushbagle22** [comment]
> I have an error in jupyter :
> 
> AttributeError: module 'clip' has no attribute 'encode_text_with_prompt_ensemble'
> 
> "encode_text_with_prompt_ensemble" is a function? How can i solve it ?
> 
> Thanks!

How  did you solved it?

**Comment by chris-vorster** [comment]
Import the CLIP code they provided in the repo, not CLIP from OpenAI (installed using pip). 

Something like: `import clip.clip as clip`
