### ISSUE TITLE
I have chinese pre-train model, how can i get the new model by this method

### ISSUE THREAD

**Issue by tnickMoxuan** [xmed-lab/CLIP_Surgery#7]

**Comment by Eli-YiLi** [comment]
If you meet the noisy activation, you can use the feature surgery. And if opposite visualization happens to your model, you are suggested to use the architecture surgery. Besides, if your model structure is the same as CLIP, you can simply use our code with your weights. If the architecture is different, please compare clip_model.py vs. clip_surgery_model.py to modify your network. Note, feature surgery is a function in clip.py, which is very easy to use.
